config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'categories/index'
  get 'categories/edit'
  get 'categories/new'
  get 'categories/show'
  root 'home#index'
  
  resources :posts
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @title = @category.name
    @posts = @category.posts
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
        @categories = Category.all
    end

    def create
        @post = Post.new(permit_params)
        if @post.save
            redirect_to posts_path, :notice => "Post saved Successfully!"
        else
            render "new"
        end
    end

    def edit
        @post = Post.find(params[:id])
        @categories = Category.all
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(permit_params)
            redirect_to post_path, :notice => "Post updated Successfully!"
        else
            render "edit"
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path, :notice => "Post deleted Successfully!"
    end

    def permit_params
        params.require(:post).permit(:title, :body, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<ul>
    <% @categories.each do |category| %>
        <li><%= link_to category.name, category %></li>
    <% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @title %></h1>
<% if @posts.each do |p| %>
  <h3><%= link_to p.title, p %></h3>
  <p><%= p.body %></p>
<% end.empty? %>
  <p>Sorry, there are no posts in this category</p>
<% end %>
  <%= link_to "Back to Categories", categories_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= value %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Ruby Posts</h1>
<% @posts.each do |post| %>
    <h3><%= link_to post.title, post %></h3>
    <p><%= post.body %><p>
    <hr>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<small><%= @post.created_at.strftime("%b %d. %Y") %></small>
<p><%= @post.body %></p>
<p>Category: <%= link_to @post.category.name, category_path(:id => @post.category.id) %></p>
<p><%= link_to "Go Back", posts_path %></p>